### ISSUE TITLE
PRACTICA 8 _ ESPECIFICACION DE REQUERIMIENTOS 

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-ggar#1]
[Practica8.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-ggar/files/10158623/Practica8.pdf)

**Comment by ElisabetRD** [comment]
28%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
